### ISSUE TITLE
Toggle floating window

### ISSUE THREAD

**Issue by ProjectInfinity** [inclement/vivarium#51]
I wasn't able to toggle a window between floating and tiled, once put into floating mode it was stuck as such. Is this intentional, a bug or not implemented yet?

**Comment by inclement** [comment]
The `tile_window` mappable command should turn a floating window back to being tiled - in the default config this is bound to meta-t and it is certainly working for me. Is this what you are trying, but it isn't working?

**Comment by ProjectInfinity** [comment]
Sorry for the late reply. I may have misunderstood. I suppose I was expecting there to be floating toggle. :)

Meta-T does re-tile the window, but doesn't toggle-untoggle floating mode on the selected window. Is there an action for toggling floating mode on the active window? Right now I need to move a window using Meta-Right click to make it float, then retile it with Meta-T.

**Comment by inclement** [comment]
Ah got it - there isn't current an action for toggling floating mode but I'm happy to add one.

The reason I didn't have one by default is mostly that it isn't something I personally planned to do, since there's no way to actually manipulate the floating window without using the mouse interaction and using the mouse would make it floating anyway. Are you expecting any specific behaviour/positioning for a window that has just been toggled to be floating?

**Comment by inclement** [comment]
I've added `float_window` and `toggle_floating` actions in #53 so closing this, but currently when you make a window floating it just stays at its previous position. Did you have a different default behaviour in mind? I'm not sure what is the most obvious choice.

**Comment by ProjectInfinity** [comment]
That sounds like correct behaviour to me.
