### ISSUE TITLE
Error on build

### ISSUE THREAD

**Issue by kkga** [inclement/vivarium#7]
I'm trying to build this on Void Linux and gettings the following error:

```
FAILED: src/vivarium.p/viv_render.c.o 
cc -Isrc/vivarium.p -Isrc -I../src -Iinclude -I../include -Iprotocols -I../protocols -I../config -Isubprojects/tomlc99 -I../subprojects/tomlc99 -I/usr/include/libdrm -I/usr/include/pixman-1 -I/usr/include/elogind -fdiagnostics-color=always -pipe -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wextra -Werror -std=c11 -g -DWLR_USE_UNSTABLE -D_POSIX_C_SOURCE=200809 -DDEBUG -DXWAYLAND -MD -MQ src/vivarium.p/viv_render.c.o -MF src/vivarium.p/viv_render.c.o.d -o src/vivarium.p/viv_render.c.o -c ../src/viv_render.c
../src/viv_render.c: In function 'viv_render_layer_view':
../src/viv_render.c:328:5: error: implicit declaration of function 'wlr_layer_surface_v1_for_each_popup'; did you mean 'wlr_layer_surface_v1_for_each_surface'? [-Werror=implicit-function-declaration]
  328 |     wlr_layer_surface_v1_for_each_popup(layer_view->layer_surface, render_surface, &rdata);
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |     wlr_layer_surface_v1_for_each_surface
cc1: all warnings being treated as errors
ninja: build stopped: subcommand failed.
```

All dependencies are installed. Wlroots is the latest stable release.
Any suggestions on how to resolve this?

**Comment by inclement** [comment]
Hmm, interesting. When you say wlroots is the latest stable release, is that definitely a build straight from the 0.12.0 tag? I've just double checked that my local wlroots is definitely 0.12.0 and that this function is also present in the original source for that tag, but it's definitely been renamed in wlroots master so more recent versions would be expected to fail with this error.

I've just merged a couple of changes to #include the layer shell header more explicitly (probably won't make any difference but can't hurt) and to enforce wlroots 0.12.0, which should at least make it clear if it's pulling wlroots from an unexpected location or something.

You could also try adding `--wrap-mode=forcefallback` to the meson command to make it download wlroots automatically. This is what the CI does, so that target version is verified working. This wouldn't be an ideal long-term solution, but could at least identify a difference with your local wlroots.

**Comment by kkga** [comment]
> wlroots is definitely 0.12.0

yes, Void's latest wlroots is built from the 0.12.0 release. 

Passing `--wrap-mode=forcefallback` did the trick though.

However, it doesn't start :sweat_smile: 

```
 Job 1, './build/src/vivarium' terminated by signal SIGSEGV (Address boundary error)
```

I don't see any errors before this line, so not sure what could be wrong. Tried starting both from Sway and TTY.

**Comment by inclement** [comment]
Uh oh, not sure what could be up here. Would you be able to get the immediate backtrace with

    gdb ./build/src/vivarium
    run
    backtrace

?

**Comment by inclement** [comment]
I've just been doing some better testing and found the default config has some things more specific to my system than intended, and can crash if some values are not good. I'll fix this within the next couple of days, it may well be causing your segfault.

**Comment by inclement** [comment]
I've fixed a bug that was causing the default config to crash, that's quite likely the segfault you were seeing.

**Comment by kkga** [comment]
Thanks! It works now.

I'm gonna play around with it, but here are a couple more errors I spotted which look like they're tied to your machine.

```
00:00:00.055 [../src/viv_server.c:523] Could not load keymap with model "pc104", layout "widecolemak", variant "widecolemak", options "ctrl:nocaps" - using default keymap instead (probably qwerty)
00:00:00.072 [../src/viv_ipc.c:12] Error opening file "/home/sandy/.viv_workspace_state.txt", skipping
```

**Comment by inclement** [comment]
Great, glad to hear it.

The xkb defaults should be corrected now in the default config.toml, and I'll fix the other reference to my own machine but they won't cause crashes any more so closing this issue.
